version: '3'

services:
  api01: &api
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '1GB'
    command: sh -c "sleep 10 && npx prisma migrate deploy"
    networks:
      - API

  api02:
    <<: *api
    ports:
      - "3001:3000"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '1.5GB'
    ports:
      - "9999:9999"
    networks:
      - API

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123pass
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 123pass
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - API

networks:
  API:
